# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0002_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='sinnombre', max_length=50),
        ),
    ]
