# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurante_app', '0001_initial'),
        ('clientes_app', '0001_initial'),
        ('catalogo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_app.Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.Profile')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_app.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.Order')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo_app.TipoProducto')),
            ],
        ),
        migrations.AddField(
            model_name='elemento_receta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.Producto_Instance'),
        ),
    ]
