# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_auto_20180328_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_instance',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
